kind: Secret
apiVersion: v1
metadata:
  name: elastic-search-es-elastic-user
data:
  elastic: ZWxhc3RpYw==
type:
  Opaque
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
spec:
  version: 8.10.0
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: elastic-search-es-default
spec:
  subdomain: elastic-search
  port:
    targetPort: 9200
  to:
    kind: Service
    name: elastic-search-es-default