apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-connector0
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: "postgres"
    database.port: 5432
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: "postgres"
    topic.prefix: "server1"
    schema.include.list: "inventory"
    key.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    key.converter.apicurio.registry.url: "http://apicurioregistry-kafkasql-service:8080"
    key.converter.apicurio.registry.auto-register: "true"
    key.converter.apicurio.registry.find-latest: "true"
    key.converter.apicurio.registry.use-id: "contentId"
    key.converter.apicurio.registry.as-confluent: "true"
    value.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    value.converter.apicurio.registry.url: "http://apicurioregistry-kafkasql-service:8080"
    value.converter.apicurio.registry.auto-register: "true"
    value.converter.apicurio.registry.find-latest: "true"
    value.converter.apicurio.registry.as-confluent: "true"
    value.converter.apicurio.registry.use-id: "contentId"
    schema.name.adjustment.mode: "avro"
    field.name.adjustment.mode: "avro"